apps/archives/urls.py
from django.urls import path
from apps.archives import views

app_name = 'archives'

urlpatterns = [
    path('', views.List.as_view(), name='list'),
    path('new', views.New.as_view(), name='new'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

apps/users/urls.py
from django.urls import path
from apps.users import views

app_name = 'users'

urlpatterns = [
    path('', views.List.as_view(), name='list'),
    path('new/', views.New.as_view(), name='new'),
    path('profile/', views.EditProfile.as_view(), name='profile'),
    path('profile/password/', views.EditPass.as_view(), name='profile-pass'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
    path('change-pass/<int:pk>/', views.ChangePass.as_view(), name='change'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.core import urls as core_urls
from apps.users import urls as users_urls
from apps.archives import urls as archives_urls
from apps.groups import urls as groups_urls
from apps.codes import urls as codes_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include(users_urls)),
    path(r'archives/', include(archives_urls)),
    path(r'groups/', include(groups_urls)),
    path(r'codes/', include(codes_urls)),
    path(r'', include(core_urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

apps/archives/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from datetime import datetime, timedelta
from apps.archives.validity import VALIDITY


class Code(models.Model):
    title = models.CharField(
        _("Title Code"), max_length=255, null=False, blank=False)
    code = models.CharField(
        _('Code'), max_length=55, blank=False, null=False)
    validity = models.IntegerField(
        _('Validity'), default=0, blank=False, null=False,
        help_text=_('In years, 0 to permanent.'))

    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    status = models.BooleanField(_("Status"), default=True)

    class Meta:
        verbose_name = _("Archive")
        verbose_name_plural = _("Archive")
        get_latest_by = 'created_at'
        ordering = ('-created_at',)

    def __str__(self):
        return "%s %s" % (self.code, self.title)


class Archive(models.Model):
    code = models.ForeignKey(
        'archives.Code', blank=True, null=False, verbose_name=_("Code"),
        on_delete=models.DO_NOTHING, related_name='code_archive')
    year = models.CharField(
        _('Year'), max_length=10, blank=True, null=True)
    box = models.CharField(
        _("Number Box"), max_length=255, null=True, blank=True)
    shelf = models.CharField(
        _("Number Shelf"), max_length=255, null=False, blank=False)
    row = models.CharField(
        _("Number Row"), max_length=255, null=False, blank=False)
    stand = models.CharField(
        _("Stand"), max_length=255, null=True, blank=True)
    dispatcher = models.CharField(
        _("Dispatcher"), max_length=255, null=True, blank=True)
    keywords = models.CharField(
        _("Keywords"), max_length=255, null=True, blank=True)
    description = models.TextField(_("Description"), null=True, blank=True)

    file = models.FileField(
        _("Archive"), upload_to='documents/', null=True, blank=True)

    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    status = models.BooleanField(_("Status"), default=True)

    creator = models.ForeignKey(
        'users.User', blank=False, null=False, verbose_name=_("User"),
        on_delete=models.DO_NOTHING, related_name='user_archive')

    class Meta:
        verbose_name = _("Archive")
        verbose_name_plural = _("Archive")
        get_latest_by = 'created_at'
        ordering = ('-created_at',)

    def __str__(self):
        return "%s %s %s" % (_("Archive"), self.code.title, self.year)

    def validity_info(self):
        if VALIDITY[self.code]:
            return "%d anos" % VALIDITY[self.code]
        elif VALIDITY[self.code] is None:
            return "Permanente"

    def validity_date(self):
        if self.code.validity != 0:
            return int(self.year) + self.code.validity
        else:
            return "∞"

    def validity_str(self):
        if self.code.validity != 0:
            return int(self.year) + self.code.validity
        else:
            return "∞"

    def is_invalid(self):
        if self.code.validity == 0:
            return False
        else:
            return self.validity_date() < datetime.now().year

    def location(self):
        return "%s: %s | %s: %s | %s: %s <br> %s: %s | %s: %s" %  \
            (
                _("Box"), self.box, _("Shelf"), self.shelf,
                _("Row"), self.row, _("Stand"), self.stand,
                _("Year"), self.year,
            )

    @property
    def has_file(self):
        return self.file is not None

apps/archives/forms.py
from django import forms
from django.conf import settings
from datetime import datetime
from apps.archives.models import Archive, Code
from django.utils.translation import ugettext_lazy as _
import re
from django.core.exceptions import ValidationError
from apps.archives.models import Archive


class FormSearch(forms.Form):
    search = forms.CharField(
        label=_('Search'), max_length=120, required=False,
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    year = forms.CharField(
        label=_('Year'), required=False,  max_length=4,
        widget=forms.TextInput(attrs={'class': 'form-control'}))


class FormArchive(forms.Form):
    reference = forms.CharField(
        label=_('Reference Archive'), max_length=120, required=False,
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    dispatcher = forms.CharField(
        label=_('Dispatcher'), max_length=120, required=False,
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    keywords = forms.CharField(
        label=_('Keywords'), max_length=120, required=False,
        help_text=_('Separated by comma.'),
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'autocomplete': 'off'}
            )
        )
    code = forms.ModelChoiceField(
        label=_('Code'),
        queryset=Code.objects.all(), required=True,
        widget=forms.Select(attrs={
            'class': 'form-control show-tick',
            'required': True, 'autocomplete': 'off'
        })
    )
    year = forms.CharField(
        label=_('Year'), required=False, initial=datetime.now().year,
        max_length=4,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'autocomplete': 'off'}
        )
    )
    is_stand = forms.BooleanField(
        label=_('Stand'), required=False, initial=False,
        widget=forms.CheckboxInput(
            attrs={
                'required': False,
                'class': 'filled-in chk-col-indigo'
                }))
    box = forms.CharField(
        label=_('Box'), max_length=120,
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'autocomplete': 'off'}
        )
    )
    stand = forms.CharField(
        label=_('Stand'), max_length=120, required=False,
        widget=forms.TextInput(
            attrs={'required': False, 'class': 'form-control'})
        )
    shelf = forms.CharField(
        label=_('Shelf'), max_length=120, required=False, initial='',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'autocomplete': 'off'}
        )
    )
    row = forms.CharField(
        label=_('Row'), max_length=120, required=True,
        widget=forms.TextInput(
            attrs={
                'required': True,
                'class': 'form-control',
                'autocomplete': 'off'
            })
        )
    description = forms.CharField(
        label=_('Description'), required=False,
        widget=forms.Textarea(
            attrs={'required': False, 'class': 'form-control'}
        )
    )
    file = forms.FileField(
        label=_("Archive"), required=False,
        widget=forms.ClearableFileInput(
            attrs={'required': False, 'class': 'form-control'}
        )
    )

    class Meta:
        fieldsets = (
          (None, {
            'fields': ('keywords', 'year')
          }),
          (None, {
            'fields': ('is_stand',)
          }),
          (None, {
            'fields': ('stand', 'shelf', 'row')
          }),
          (None, {
            'fields': ('code', 'box')
          }),
          (None, {
            'fields': ('description',)
          }),
          (None, {
            'fields': ('file',)
          }),
          (None, {
            'fields': ('dispatcher', )
          }),
        )

apps/archives/views.py
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator
from django.views.generic import FormView, RedirectView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from apps.archives.forms import FormArchive, FormSearch
from apps.archives.models import Archive
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.db.models import Q
import datetime
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.decorators import user_passes_test
from django.utils.translation import activate


class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        activate('pt-br')
        return super(LoginRequiredMixin, self)\
            .dispatch(request, *args, **kwargs)

class LoginRequiredMixin2(object):
    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        activate('pt-br')
        return super(LoginRequiredMixin2, self)\
            .dispatch(request, *args, **kwargs)


class List(LoginRequiredMixin, ListView):
    template_name = "archives/list.html"
    model = Archive
    context_object_name = 'archives'
    paginate_by = 25

    def get_queryset(self, **kwargs):
        query = Q(status=True)

        if self.request.GET.get('search', None):
            query.add(
                Q(code__code__icontains=self.request.GET['search']) |
                Q(code__title__icontains=self.request.GET['search']) |
                Q(description__icontains=self.request.GET['search']) |
                Q(keywords__icontains=self.request.GET['search']), Q.AND)

        if self.request.GET.get('year', None):
            query.add(Q(year=self.request.GET['year']), Q.AND)

        return Archive.objects.filter(query).order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super(List, self).get_context_data(**kwargs)
        context.update(dict(form_search=FormSearch(self.request.GET)))
        return context


class New(LoginRequiredMixin, FormView):
    template_name = 'archives/form.html'
    form_class = FormArchive
    success_url = reverse_lazy('archives:list')

    def form_valid(self, form):
        data = form.cleaned_data

        archive = Archive(
            code=data['code'],
            box=data['box'],
            shelf=data['shelf'],
            stand=data['stand'],
            row=data['row'],
            keywords=data['keywords'],
            year=data['year'],
            description=data['description'],
            creator=self.request.user,
            file=data['file'],
            dispatcher=data['dispatcher']
        )

        archive.save()

        msg = "%s %s %s" % (
            _("Archive"), archive.code, _("added successfully!"))
        messages.add_message(self.request, messages.SUCCESS, msg)

        return super(New, self).form_valid(form)


class Edit(LoginRequiredMixin, FormView):
    template_name = "archives/form.html"
    form_class = FormArchive
    success_url = reverse_lazy('archives:list')

    def get_object(self):
        return get_object_or_404(Archive, id=self.kwargs.get('pk'))

    def get_initial(self):
        self.initial = model_to_dict(self.get_object())
        return self.initial.copy()

    def form_valid(self, form):
        data = form.cleaned_data
        archive = self.get_object()

        archive.code = data['code']
        archive.box = data['box']
        archive.shelf = data['shelf']
        archive.row = data['row']
        archive.stand = data['stand']
        archive.year = data['year']
        archive.keywords = data['keywords']
        archive.description = data['description']
        archive.dispatcher = data['dispatcher']

        if data['file']:
            archive.file = data['file']

        archive.save()

        msg = "%s %s %s" % (
            _("Archive"), archive.code, _("updated successfully!"))
        messages.add_message(self.request, messages.SUCCESS, msg)

        return super(Edit, self).form_valid(form)


class Detail(LoginRequiredMixin, DetailView):
    slug_field = 'id'
    model = Archive
    context_object_name = 'archive'
    template_name = "archives/detail.html"


class Delete(LoginRequiredMixin2, DeleteView):
    model = Archive
    success_url = reverse_lazy('archives:list')
    template_name = 'archives/delete.html'
    success_message = _('Archive deleted successfully')
    slug_field = 'pk'

apps/archives/templates/archives/delete.html
{% extends "components/base.html" %}

{% load i18n %}

{% block content %}

  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
          <h3>{% trans "You want to delete the file"%}  "{{ object }}" ?</h3>
        </div>
        <div class="body">
          <form method="post" action="">
          {% csrf_token %}
          <br>
          <div class="row">
            <a class="btn btn-danger waves-effect" href="{% url 'archives:list' %}">
              {% trans "Cancel"%}
            </a>
            <button type="submit" value="" class="btn green" >
              {% trans "Delete"%}
            </button>
          </div>
        </form>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

apps/archives/templates/archives/detail.html
{% extends "components/base.html" %}

{% load i18n %}

{% load static %}

{% block extra_css %}
  <link href="{% static 'adminbsb-materialdesign/plugins/sweetalert/sweetalert.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
          <h2>{% trans "Detail" %} {{archive.title}}</h2>
        </div>
        <div class="body">
          <p><b>{% trans "Reference" %}: </b> {{archive.reference}}</p>
          <p><b>{% trans "Code" %}: </b> {{archive.code.title}}</p>
          <p><b>{% trans "Year" %}: </b> {{archive.year}}</p>
          <p><b>{% trans "Validity" %}: </b>
            <span class="badge {% if a.is_invalid %}bg-red{% else %}bg-green{% endif %}">
              {{archive.validity_date}}
            </span>
          </p>
          <p><b>{% trans "Box" %}: </b> {{archive.box}}</p>
          <p><b>{% trans "Shelf" %}: </b> {{archive.shelf}}</p>
          <p><b>{% trans "Stand" %}: </b> {{archive.stand}}</p>
          <p><b>{% trans "Keywords" %}: </b> {{archive.keywords}}</p>
          <p><b>{% trans "Descripition" %}: </b> {{archive.description}}</p>
          {% if archive.file %}
            <p><b>{% trans "File" %}: </b> <a href="{{archive.file.url}}" target="_blank" > {% trans "See archive" %} </a></p>
          {% else %}
            <p><b>{% trans "File" %}: </b> <a href="#" > {% trans "No File" %} </a></p>
          {% endif %}
        </div>
      </div>
    </div>

  </div>
{% endblock %}

{% block extra_js %}


{% endblock %}

apps/archives/templates/archives/form.html
{% extends "components/base.html" %}

{% load i18n %}

{% load static %}

{% block extra_css %}
  <link href="{% static 'plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
<div class="block-header">
</div>
<!-- Input -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        {% trans "FORM ARCHIVE" as form_archive %}
        <h2>{{ form_archive | upper }}</h2>
      </div>
      <div class="body">
        {% include "components/messages.html" with form=form %}
          <form id="form_email" class="" action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for fieldset in form.fieldsets %}
            <div class="row">
                {% for field in fieldset %}
                <div class="col-md-6">
                  <div class="form-group form-float">
                    {% if field.field.widget.input_type == 'select' %}
                      {{field}}
                    {% elif field.field.widget.input_type == 'checkbox' %}
                      {{field}}
                      <label for="{{field.auto_id}}">{{field.label}}</label>
                    {% else %}
                      <div class="form-line">{{field}}
                        <label class="form-label">{{field.label}}</label>
                      </div>
                    {% endif %}

                    {% if field.help_text  %}
                      <p class="help-text" id="{{field.id_for_label}}">
                        {{field.help_text|safe}}
                      </p>
                    {% endif %}
                  </div>
                </div>
                {% endfor %}
            </div>
          {% endfor %}
          <a href="{% url 'users:list' %}" class="btn btn-danger waves-effect">
            {% trans "Cancel" %}
          </a>
          <button type="submit" class="btn btn-primary waves-effect">{% trans "Send" %}</button>
          </form>
      </div>
    </div>
  </div>

</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'plugins/momentjs/moment.js' %}"></script>
<script src="{% static 'plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js' %}"></script>
<script>
  $(function () {
    /*
    $('#id_validity').bootstrapMaterialDatePicker({
        format: 'DD/MM/YYYY',
        clearButton: true,
        weekStart: 1,
        time: false
      });
    */

    $('#id_is_stand').change(function(){
      if ($('#id_is_stand').is(":checked")) {
        $('#id_shelf').parent().parent().parent().hide();
        // $('#id_shelf').val('');
        $('#id_stand').parent().parent().parent().show();
        // $('#id_stand').val('');
      } else {
        $('#id_stand').parent().parent().parent().hide();
        // $('#id_stand').val('');
        $('#id_shelf').parent().parent().parent().show();
        // $('#id_shelf').val('');
      }
    });

    $('#id_is_stand').trigger('change');
  });
</script>

{% endblock %}

apps/archives/templates/archives/list.html
{% extends "components/base.html" %}

{% load i18n %}

{% load form_tags %}

{% block content %}

<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        {% trans "Search" as search %}
        <h2>{{search | upper}}</h2>
      </div>
      <div class="body">
        <form method="get" action="">
          <div class="row clearfix">
            {% for field in form_search %}
              <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                <div class="form-group form-float">
                {% if field.field.widget.input_type == 'select' %}
                  {{field}}
                {% elif field.field.widget.input_type == 'checkbox' %}
                  {{field}}
                  <label for="{{field.auto_id}}">{{field.label}}</label>
                  {% elif field.field.widget.input_type == 'text' %}
                  <div class="form-line">{{field}}
                    <label class="form-label">{{field.label}}</label>
                  </div>
                {% endif %}
                </div>
              </div>
            {% endfor %}

            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
              <!--input type="checkbox" id="remember_me_4" class="filled-in">
              <label for="remember_me_4">Remember Me</label-->
              <button type="submit" class="btn btn-primary btn-lg m-l-15 waves-effect">{{search}}</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        {% trans "Archives" as archives_title %}
        <h2>{{ archives_title | upper }}</h2>
      </div>
      <div class="body table-responsive table-striped">
        {% include "components/messages.html" with form=None %}
        <table class="table">
          {% trans "Code" as code %}
          {% trans "Valdity" as validity %}
          {% trans "Keywords" as keywords %}
          {% trans "Location" as location %}
          {% trans "Actions" as action %}
          {% trans "Year" as year %}
          <thead>
            <tr>
              <th>{{ code | upper }}</th>
              <th>{{ validity | upper }}</th>
              <th>{{ keywords | upper }}</th>
              <th>{{ location | upper  }}</th>
              <th>{{ actions | upper }}</th>
            </tr>
          </thead>
          <tbody>
            {% for a in archives %}
              <tr class="">
                <td>{{a.code.code}} - {{a.code.title}}</td>
                <td>
                  <span class="badge {% if a.is_invalid %}bg-red{% else %}bg-green{% endif %}">
                    {{a.validity_date}}
                  </span>
                </td>
                <td>{% if a.keywords %}{{ a.keywords }}{%endif%}</td>
                <td>{{a.location | safe }}</td>
                <td>
                  <div class="btn-group " role="group">
                    <a href="{% url 'archives:detail' a.id %}" class="btn btn-default waves-effect btn-xs" target="_blank"><i class="material-icons">visibility</i></a>
                    {% if a.file %}
                      <a href="{{a.file.url}}" class="btn btn-default waves-effect btn-xs" target="_blank"><i class="material-icons">insert_drive_file</i></a>
                    {% else %}
                      <a href="#" class="btn btn-default waves-effect btn-xs" disabled target="_blank"><i class="material-icons">insert_drive_file</i></a>
                    {% endif %}
                    <a href="{% url 'archives:edit' a.id %}" class="btn btn-primary waves-effect btn-xs"><i class="material-icons">create</i></a>
                    {% if user.is_superuser %}
                      <a href="{% url 'archives:delete' a.id %}" class="btn btn-danger waves-effect btn-xs"><i class="material-icons">delete</i></a>
                    {% endif %}
                  </div>
                </td>
            {% endfor %}
        </table>
      </div>
    </div>
    <div class="footer">
      {% if is_paginated %}
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="waves-effect" ><a href="?{% url_replace page=page_obj.previous_page_number %}"><i class="material-icons">chevron_left</i></a></li>
          {% else %}
            <li class="disabled"><a href="#"><i class="material-icons">chevron_left</i></a></li>
          {% endif %}
            <li class="">
                <span>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
            </li>
          {% if page_obj.has_next %}
              <li class="waves-effect"><a href="?{% url_replace page=page_obj.next_page_number %}"><i class="material-icons">chevron_right</i></a></li>
          {% else %}
            <li class="waves-effect"><a href="#"><i class="material-icons">chevron_right</i></a></li>
          {% endif %}
        </ul>
      {% endif %}
    </div>
    </div>
  </div>
</div>

{% endblock %}