apps/archives/urls.py
from django.urls import path
from apps.archives import views

app_name = 'archives'

urlpatterns = [
    path('', views.List.as_view(), name='list'),
    path('new', views.New.as_view(), name='new'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

apps/codes/urls.py
from django.urls import path
from apps.codes import views

app_name = 'codes'

urlpatterns = [
    path('', views.List.as_view(), name='list'),
    path('new', views.New.as_view(), name='new'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

apps/users/urls.py
from django.urls import path
from apps.users import views

app_name = 'users'

urlpatterns = [
    path('', views.List.as_view(), name='list'),
    path('new/', views.New.as_view(), name='new'),
    path('profile/', views.EditProfile.as_view(), name='profile'),
    path('profile/password/', views.EditPass.as_view(), name='profile-pass'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
    path('change-pass/<int:pk>/', views.ChangePass.as_view(), name='change'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.core import urls as core_urls
from apps.users import urls as users_urls
from apps.archives import urls as archives_urls
from apps.groups import urls as groups_urls
from apps.codes import urls as codes_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include(users_urls)),
    path(r'archives/', include(archives_urls)),
    path(r'groups/', include(groups_urls)),
    path(r'codes/', include(codes_urls)),
    path(r'', include(core_urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

apps/codes/forms.py
from django import forms
from django.conf import settings
from datetime import datetime
from apps.archives.models import Code
from django.utils.translation import ugettext_lazy as _
import re
from django.core.exceptions import ValidationError

class FormSearch(forms.Form):
    search = forms.CharField(
        label=_('Search'), max_length=120, required=False,
        widget=forms.TextInput(attrs={'class': 'form-control' }))


class FormCode(forms.Form):
    title = forms.CharField(
        label=_('Title Archive'), max_length=120, required=True,
        widget=forms.TextInput(attrs={'class': 'form-control' }))
    code = forms.CharField(
        label=_('Code'), max_length=120, required=True,
        widget=forms.TextInput(attrs={'class': 'form-control' }))
    validity = forms.IntegerField(
        label=_('Validity'), required=True, initial=0,
        help_text=_('In years, 0 to permanent.'),
        widget=forms.NumberInput(attrs={'class': 'form-control' }))

    class Meta:
        fieldsets = (
          (None, {
            'fields': ('title',)
          }),
          (None, {
            'fields': ('code',)
          }),
          (None, {
            'fields': ('validity',)
          }),
        )

apps/codes/views.py
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator
from django.views.generic import FormView, RedirectView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from apps.codes.forms import FormCode, FormSearch
from apps.archives.models import Code
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.db.models import Q
from django.utils.translation import activate
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.decorators import user_passes_test
import datetime


class LoginRequiredMixin(object):
    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        activate('pt-br')
        return super(LoginRequiredMixin, self)\
            .dispatch(request, *args, **kwargs)


class List(LoginRequiredMixin, ListView):
    template_name = "codes/list.html"
    model = Code
    context_object_name = 'codes'
    paginate_by = 10

    def get_queryset(self, **kwargs):
        query = Q(status=True)

        if self.request.GET.get('search', None):
            query.add(Q(code__icontains=self.request.GET['search']), Q.AND)

        return Code.objects.filter(query)

    def get_context_data(self, **kwargs):
        context = super(List, self).get_context_data(**kwargs)
        context.update(dict(form_search=FormSearch(self.request.GET)))
        return context


class New(LoginRequiredMixin, FormView):
    template_name = 'codes/form.html'
    form_class = FormCode
    success_url = reverse_lazy('codes:list')

    def form_valid(self, form):
        data = form.cleaned_data

        code = Code(
            title=data['title'],
            code=data['code'],
            validity=data['validity'],
        )

        code.save()

        msg ="%s %s %s" % (
            _("Archive"), code.title, _("added successfully!"))
        messages.add_message(self.request, messages.SUCCESS, msg)

        return super(New, self).form_valid(form)


class Edit(LoginRequiredMixin, FormView):
    template_name = "codes/form.html"
    form_class = FormCode
    success_url = reverse_lazy('codes:list')

    def get_object(self):
        return get_object_or_404(Code, id=self.kwargs.get('pk'))

    def get_initial(self):
        self.initial = model_to_dict(self.get_object())
        return self.initial.copy()

    def form_valid(self, form):
        data = form.cleaned_data
        code = self.get_object()

        code.title=data['title']
        code.code=data['code']
        code.validity=data['validity']

        code.save()

        msg = "%s alterado com sucesso." % code.title
        messages.add_message(self.request, messages.SUCCESS, msg)

        return super(Edit, self).form_valid(form)


class Detail(LoginRequiredMixin, DetailView):
    slug_field = 'id'
    model = Code
    context_object_name = 'code'
    template_name = "codes/detail.html"


class Delete(LoginRequiredMixin, DeleteView):
    model = Code
    success_url = reverse_lazy('codes:list')
    template_name = 'codes/delete.html'
    success_message = _('Code deleted successfully')
    slug_field = 'pk'

apps/codes/templates/codes/delete.html
{% extends "components/base.html" %}

{% load i18n %}

{% block content %}


<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>{% trans "Delete code" %}</h2>
      </div>
      <div class="body">
        <h3>{% trans "You want to delete the file" %}  "{{ object }}" ?</h3>
        <form method="post" action="">
          {% csrf_token %}
          <br>
          <div class="row">
            <a class="btn red" href="{% url 'archives:list' %}">
              <i class="fa fa-fw fa-ban" aria-hidden="true"></i>
              {% trans "Cancel"%}
            </a>
            <button type="submit" value="" class="btn green" >
              <i class="fa fa-fw fa-trash" aria-hidden="true"></i>
              {% trans "Delete"%}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

apps/codes/templates/codes/detail.html
{% extends "components/base.html" %}

{% load i18n %}

{% load static %}

{% block extra_css %}
  <link href="{% static 'plugins/sweetalert/sweetalert.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
          <h2>{% trans "Detail" %} {{code.title}}</h2>
        </div>
        <div class="body">
          <p><b>{% trans "Title" %}: </b> {{code.title}}</p>
          <p><b>{% trans "Validity" %}: </b> {{code.validity}}</p>
          <p><b>{% trans "Code" %}: </b> {{code.code}}</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block extra_js %}


{% endblock %}

apps/codes/templates/codes/form.html
{% extends "components/base.html" %}

{% load i18n %}

{% load static %}

{% block extra_css %}
  <link href="{% static 'plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
<div class="block-header">
</div>
<!-- Input -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        {% trans "form code" as form_code %}
        <h2>{{form_code | upper}}</h2>
      </div>
      <div class="body">
        {% include "components/messages.html" with form=form %}
          <form id="form_email" class="" action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for fieldset in form.fieldsets %}
            <div class="row">
                {% for field in fieldset %}
                <div class="col-sm-6">
                  <div class="form-group form-float">
                    {% comment %}
                      {% if field.errors %}
                        <p>{{ field.errors }}</p>
                      {% endif %}
                    {% endcomment %}

                    {% if field.field.widget.input_type == 'select' %}
                      {{field}}
                    {% elif field.field.widget.input_type == 'checkbox' %}
                      {{field}}
                      <label for="{{field.auto_id}}">{{field.label}}</label>
                    {% else %}
                      <div class="form-line">{{field}}
                        <label class="form-label">{{field.label}}</label>
                      </div>
                    {% endif %}

                    {% if field.help_text  %}
                      <p class="help-text" id="{{field.id_for_label}}">
                        {{field.help_text|safe}}
                      </p>
                    {% endif %}
                  </div>
                </div>
                {% endfor %}
            </div>
          {% endfor %}
          <a href="{% url 'users:list' %}" class="btn btn-danger waves-effect">
            {% trans "Cancel" %}
          </a>
          <button type="submit" class="btn btn-primary waves-effect">{% trans "Send" %}</button>
          </form>
      </div>
    </div>
  </div>

</div>
{% endblock %}

{% block extra_js %}

{% endblock %}

apps/codes/templates/codes/list.html
{% extends "components/base.html" %}

{% load i18n %}

{% load form_tags %}

{% block content %}

<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        {% trans "Search" as search %}
        <h2>{{search | upper}}</h2>
      </div>
      <div class="body">
        <form method="get" action="">
          <div class="row clearfix">
            {% for field in form_search %}
              <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
              <div class="form-group form-float">
              {% if field.field.widget.input_type == 'select' %}
                {{field}}
              {% elif field.field.widget.input_type == 'checkbox' %}
                {{field}}
                <label for="{{field.auto_id}}">{{field.label}}</label>
                {% elif field.field.widget.input_type == 'text' %}
                <div class="form-line">{{field}}
                  <label class="form-label">{{field.label}}</label>
                </div>
              {% endif %}
              </div>
              </div>
            {% endfor %}

            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
              <button type="submit" class="btn btn-primary btn-lg m-l-15 waves-effect">{{ search }}</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        {% trans "Codes" as codes_title %}
        <h2>{{codes_title | upper}}</h2>
      </div>
      <div class="body table-responsive table-striped">
        {% include "components/messages.html" with form=None %}
        <table class="table">
          {% trans "Title" as title %}
          {% trans "Code" as code %}
          {% trans "Validity" as validity %}
          {% trans "Actions" as actions %}
          <thead>
            <tr>
              <th>{{title|upper}}</th>
              <th>{{code|upper}}</th>
              <th>{{validity|upper}}</th>
              <th>{{actions|upper}}</th>
            </tr>
          </thead>
          <tbody>
            {% for c in codes %}
              <tr class="">
                <td>{{c.title}}</td>
                <td>{{c.code}}</td>
                <td>
                  <span>
                    {{c.validity}}
                  </span>
                </td>
                <td>
                  <div class="btn-group" role="group">
                    <a href="{% url 'codes:edit' c.id %}" class="btn btn-primary waves-effect btn-xs"><i class="material-icons">create</i></a>
                    <a href="{% url 'codes:delete' c.id %}" class="btn btn-danger waves-effect btn-xs"><i class="material-icons">delete</i></a>
                  </div>
                </td>
            {% endfor %}
        </table>
      </div>
    </div>
    <div class="footer">
      {% if is_paginated %}
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="waves-effect" ><a href="?{% url_replace page=page_obj.previous_page_number %}"><i class="material-icons">chevron_left</i></a></li>
          {% else %}
            <li class="disabled"><a href="#"><i class="material-icons">chevron_left</i></a></li>
          {% endif %}
            <li class="">
                <span>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
            </li>
          {% if page_obj.has_next %}
              <li class="waves-effect"><a href="?{% url_replace page=page_obj.next_page_number %}"><i class="material-icons">chevron_right</i></a></li>
          {% else %}
            <li class="waves-effect"><a href="#"><i class="material-icons">chevron_right</i></a></li>
          {% endif %}
        </ul>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}