apps/users/urls.py
from django.urls import path
from apps.users import views

app_name = 'users'

urlpatterns = [
    path('', views.List.as_view(), name='list'),
    path('new/', views.New.as_view(), name='new'),
    path('profile/', views.EditProfile.as_view(), name='profile'),
    path('profile/password/', views.EditPass.as_view(), name='profile-pass'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
    path('change-pass/<int:pk>/', views.ChangePass.as_view(), name='change'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.core import urls as core_urls
from apps.users import urls as users_urls
from apps.archives import urls as archives_urls
from apps.groups import urls as groups_urls
from apps.codes import urls as codes_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include(users_urls)),
    path(r'archives/', include(archives_urls)),
    path(r'groups/', include(groups_urls)),
    path(r'codes/', include(codes_urls)),
    path(r'', include(core_urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth.models import AbstractBaseUser, \
    _user_get_all_permissions, BaseUserManager, Group, \
    Permission, _user_has_perm, _user_has_module_perms, \
    PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
import re
from django.core import validators
from django.core.mail import send_mail


class UserManager(BaseUserManager):
    def _create_user(
        self, username, email, password, is_staff,
            is_superuser, **extra_fields):
        now = timezone.now()
        if not username:
            raise ValueError(_('The given username must be set'))
        email = self.normalize_email(email)
        user = self.model(
            username=username, email=email,
            is_staff=is_staff, is_active=False,
            is_superuser=is_superuser, last_login=now,
            date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        return self._create_user(
            username, email, password, False, False, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        user = self._create_user(
            username, email, password, True, True, **extra_fields)
        user.is_active = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    GENDER_CHOICE = (
        ('', '---------'),
        ('M', _('Male')),
        ('F', _('Female')),
    )

    username = models.CharField(
        _('username'), max_length=255, unique=True,
        help_text=_(
            'Required. 30 characters or fewer. Letters,'
            'numbers and @/./+/-/_ characters'),
        validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                _('Enter a valid username.'), _('invalid'))
        ])
    first_name = models.CharField(
        _('First name'), max_length=255, blank=True)
    last_name = models.CharField(
        _('Last name'), max_length=255, blank=True)
    cpf = models.CharField(
        _('CPF'), max_length=255, blank=True, null=True)
    email = models.EmailField(
        _('Email address'), unique=True)
    gender = models.CharField(
        _('Gender'), max_length=2, choices=GENDER_CHOICE, blank=True, null=True)
    birth = models.DateField('Nascimento', null=True, blank=True)
    phone = models.CharField(
        _('Phone'), max_length=55, blank=True, null=True)
    hash_util = models.CharField(
        _('Hash'), max_length=255, blank=True, null=True)
    is_staff = models.BooleanField(
        _('staff status'), default=False,
        help_text=_(
            'Designates whether the user'
            ' can log into this admin site.'))
    is_active = models.BooleanField(
        _('active'), default=False,
        help_text=_(
            'Designates whether this user should be treated as active.'
            ' Unselect this instead of deleting accounts.'))
    is_member = models.BooleanField('Membro', default=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    description = models.TextField("Texto", null=True, blank=True)
    photo = models.ImageField(
        'Foto', upload_to='uploads/users/', null=True, blank=True)
    created = models.DateTimeField(
        _('created'), auto_now_add=True)
    changed = models.DateTimeField(
        _('changed'), auto_now=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']
    objects = UserManager()

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')
        # app_label = "myauth"
    @property
    def full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def email_user(self, subject, message, from_email=None):
        send_mail(subject, message, from_email, [self.email])

    def get_avatar(self):
        if self.avatar:
            return self.avatar.url
        else:
            return '/static/img/avatar.png'

    def get_group_permissions(self, obj=None):
        permissions = set()
        for backend in auth.get_backends():
            if hasattr(backend, "get_group_permissions"):
                if obj is not None:
                    permissions.update(backend.get_group_permissions(self,
                                                                     obj))
                else:
                    permissions.update(backend.get_group_permissions(self))
        return permissions

    def get_all_permissions(self, obj=None):
        return _user_get_all_permissions(self, obj)

    def has_perm(self, perm, obj=None):
        # Ativo se o superusuario tiver todas as permissoes.
        if self.is_active and self.is_superuser:
            return True

        return _user_has_perm(self, perm, obj)

    def has_perms(self, perm_list, obj=None):
        for perm in perm_list:
            if not self.has_perm(perm, obj):
                return False
        return True

    def has_module_perms(self, app_label):
        if self.is_active and self.is_superuser:
            return True

        return _user_has_module_perms(self, app_label)

apps/users/views.py
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator
from django.views.generic import FormView, RedirectView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.shortcuts import get_object_or_404
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from apps.users.forms import FormCreate, FormEdit, \
    FormSearch, FormPass, FormProfile
from django.forms.models import model_to_dict
from apps.users.models import User
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _, activate
import datetime
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test


class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        activate('pt-br')
        return super(LoginRequiredMixin, self)\
            .dispatch(request, *args, **kwargs)


class LoginRequiredMixin2(object):
    @method_decorator(login_required)
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        activate('pt-br')
        return super(LoginRequiredMixin2, self)\
            .dispatch(request, *args, **kwargs)


class New(LoginRequiredMixin2, FormView):
    template_name = 'users/form.html'
    form_class = FormCreate
    success_url = reverse_lazy('users:list')

    def form_valid(self, form):
        data = form.cleaned_data

        user = User(
            username=data['email'],
            first_name=data['first_name'],
            last_name=data['last_name'],
            cpf=data['cpf'],
            email=data['email'],
            gender=data['gender'],
            birth=data['birth'],
            phone=data['phone'],
            is_superuser=data['is_superuser'],
            is_active=data['is_active']
        )

        user.set_password(data['password_confirm'])

        user.save()

        msg = "%s %s %s" % (
            _("User"), user.get_short_name(), _("added successfully!"))
        messages.add_message(self.request, messages.SUCCESS, msg)

        return super(New, self).form_valid(form)


class Edit(LoginRequiredMixin2, FormView):
    template_name = "users/form.html"
    form_class = FormEdit
    success_url = reverse_lazy('users:list')

    def get_object(self):
        return get_object_or_404(User, id=self.kwargs.get('pk'))

    def get_initial(self):
        user = self.get_object()
        initial = model_to_dict(user)
        if user.birth:
            initial['birth'] = user.birth.strftime('%d/%m/%Y')
        return initial.copy()

    def form_valid(self, form):
        data = form.cleaned_data
        user = self.get_object()

        user.first_name = data['first_name']
        user.last_name = data['last_name']

        if user.cpf != data['cpf']:
            user.cpf = data['cpf']

        if user.email != data['email']:
            user.email = data['email']
            user.username = data['email']

        user.first_name = data['first_name']
        user.last_name = data['last_name']
        user.gender = data['gender']
        user.birth = data['birth']
        user.phone = data['phone']
        user.is_superuser = data['is_superuser']
        user.is_active = data['is_active']

        user.save()

        msg = "%s %s %s" % (
            _("User"), user.get_short_name(), _("updated successfully!"))
        messages.add_message(self.request, messages.SUCCESS, msg)

        return super(Edit, self).form_valid(form)


class EditProfile(LoginRequiredMixin, FormView):
    template_name = "users/form_profile.html"
    form_class = FormProfile
    success_url = reverse_lazy('core:home')

    def get_object(self):
        return get_object_or_404(User, id=self.kwargs.get('pk'))

    def get_initial(self):
        initial = model_to_dict(self.request.user)
        if self.request.user.birth:
            initial['birth'] = self.request.user.birth.strftime('%d/%m/%Y')
        return initial.copy()

    def form_valid(self, form):
        data = form.cleaned_data
        user = self.request.user

        user.first_name = data['first_name']
        user.last_name = data['last_name']

        if user.cpf != data['cpf']:
            user.cpf = data['cpf']

        if user.email != data['email']:
            user.email = data['email']
            user.username = data['email']

        user.first_name = data['first_name']
        user.last_name = data['last_name']
        user.gender = data['gender']
        user.birth = data['birth']
        user.phone = data['phone']

        user.save()

        msg = "%s %s %s" % (
            _("User"), user.get_short_name(), _("updated successfully!"))
        messages.add_message(self.request, messages.SUCCESS, msg)

        return super(EditProfile, self).form_valid(form)


class EditPass(LoginRequiredMixin, FormView):
    template_name = "users/form_pass.html"
    form_class = FormPass
    success_url = reverse_lazy('core:home')

    def form_valid(self, form):
        data = form.cleaned_data
        user = self.request.user

        user.set_password(data['password_confirm'])

        user.save()

        msg = "%s %s %s" % (
            _("User"), user.get_short_name(),
            _("password changed successfully!"))
        messages.add_message(self.request, messages.SUCCESS, msg)

        return super(EditPass, self).form_valid(form)


class List(LoginRequiredMixin2, ListView):
    template_name = "users/list.html"
    model = User
    context_object_name = 'users'
    paginate_by = 25

    def get_queryset(self, **kwargs):
        query = Q(is_active=True)

        if self.request.GET.get('search', None):
            query.add(
                Q(first_name__icontains=self.request.GET['search']) |
                Q(last_name__icontains=self.request.GET['search']) |
                Q(email__icontains=self.request.GET['search']), Q.AND)

        return User.objects.filter(query).order_by('-created')

    def get_context_data(self, **kwargs):
        context = super(List, self).get_context_data(**kwargs)
        context.update(dict(form_search=FormSearch(self.request.GET)))
        return context


class Detail(LoginRequiredMixin2, DetailView):
    slug_field = 'id'
    model = User
    context_object_name = 'user'
    template_name = "users/detail.html"


class Delete(LoginRequiredMixin2, DeleteView):
    model = User
    success_url = reverse_lazy('users:list')
    template_name = 'users/delete.html'
    success_message = _("User added successfully!")
    slug_field = 'pk'


class ChangePass(LoginRequiredMixin2, FormView):
    template_name = 'users/form_pass.html'
    form_class = FormPass
    success_url = reverse_lazy('users:list')

    def get_object(self):
        return get_object_or_404(User, id=self.kwargs.get('pk'))

    def form_valid(self, form):
        data = form.cleaned_data
        user = self.get_object()

        user.set_password(data['password_confirm'])

        user.save()

        msg = "%s %s %s" % (
            _("User"), user.get_short_name(),
            _("password changed successfully!"))
        messages.add_message(self.request, messages.SUCCESS, msg)

        return super(ChangePass, self).form_valid(form)

apps/users/templates/users/delete.html
{% extends "components/base.html" %}

{% block content %}

<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h3>Você deseja deletar o user  "{{ object }}" ?</h3>
      </div>
      <form method="post" action="">
        {% csrf_token %}
        <br>
        <div class="row">
          <a class="btn red" href="{% url 'users:list' %}">
            <i class="fa fa-fw fa-ban" aria-hidden="true"></i> Cancelar
          </a>
          <button type="submit" value="" class="btn green" >
            <i class="fa fa-fw fa-trash" aria-hidden="true"></i> Deletar
          </button>
        </div>
      </form>
    </div>
  </div>
</div>


{% endblock %}

apps/users/templates/users/detail.html
{% extends "components/base.html" %}

{% load i18n %}
{% load static %}

{% block extra_css %}
  <link href="{% static 'plugins/sweetalert/sweetalert.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
  <div class="block-header">
    <h2>{% trans 'Details' %}</h2>
  </div>
  <!-- Input -->
  <div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
          <h2>Detail {{user.full_name}}</h2>
        </div>
        <div class="body">
          <p><b>First Name: </b> {{user.first_name}}</p>
          <p><b>Last Name: </b> {{user.last_name}}</p>
          <p><b>Gender: </b> {{user.gender }}</p>
          <p><b>Birth:  </b> {{user.birth}}</p>
          <p><b>Phone: </b> {{user.phone}}</p>
          <br>
          <br>
        </div>
      </div>
    </div>

  </div>


  <div class="modal fade" id="defaultModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="defaultModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sodales orci ante, sed ornare eros vestibulum ut. Ut accumsan
                vitae eros sit amet tristique. Nullam scelerisque nunc enim, non dignissim nibh faucibus ullamcorper.
                Fusce pulvinar libero vel ligula iaculis ullamcorper. Integer dapibus, mi ac tempor varius, purus
                nibh mattis erat, vitae porta nunc nisi non tellus. Vivamus mollis ante non massa egestas fringilla.
                Vestibulum egestas consectetur nunc at ultricies. Morbi quis consectetur nunc.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link waves-effect">SAVE CHANGES</button>
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
            </div>
        </div>
    </div>
  </div>



{% endblock %}

{% block extra_js %}


{% endblock %}

apps/users/templates/users/form.html
{% extends "components/base.html" %}

{% load i18n %}

{% load static %}

{% block extra_css %}
  <link href="{% static 'plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
<div class="block-header">
</div>
<!-- Input -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        {% trans 'Form user' as form_user %}
        <h2>{{form_user | upper}}</h2>
      </div>
      <div class="body">
        {% include "components/messages.html" with form=form %}
        <form id="form_email" class="" action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for fieldset in form.fieldsets %}
            <div class="row">
              {% for field in fieldset %}
              <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group form-float">
                  {% comment %}
                    {% if field.errors %}
                      <p>{{ field.errors }}</p>
                    {% endif %}
                  {% endcomment %}

                  {% if field.field.widget.input_type == 'select' or field.field.widget.input_type == 'hidden' %}
                    {{field}}
                  {% elif field.field.widget.input_type == 'checkbox' %}
                    {{field}}
                    <label for="{{field.auto_id}}">{{field.label}}</label>
                  {% else %}
                    <div class="form-line">{{field}}
                      <label class="form-label">{{field.label}}</label>
                    </div>
                  {% endif %}

                  {% if field.help_text  %}
                    <p class="help-text" id="{{field.id_for_label}}">
                      {{field.help_text|safe}}
                    </p>
                  {% endif %}
                </div>
              </div>
              {% endfor %}
            </div>
          {% endfor %}
          <a href="{% url 'users:list' %}" class="btn btn-danger waves-effect">{% trans 'Cancel'%}</a>
          <button type="submit" class="btn btn-primary waves-effect">{% trans 'Send' %}</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'plugins/momentjs/moment.js' %}"></script>
<script src="{% static 'plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js' %}"></script>
<script>
  $(function () {
    $('#id_birth').bootstrapMaterialDatePicker({
        format: 'DD/MM/YYYY',
        clearButton: true,
        weekStart: 1,
        time: false
    });
  });
</script>

{% endblock %}

apps/users/templates/users/form_pass.html
{% extends "components/base.html" %}

{% load i18n %}

{% load static %}

{% block extra_css %}
  <link href="{% static 'plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
<div class="block-header">
</div>
<!-- Input -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        {% trans 'Form password' as form_pass %}
        <h2>{{form_pass | upper}}</h2>
      </div>
      <div class="body">
        {% include "components/messages.html" with form=form %}
        <form id="form_email" class="" action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for fieldset in form.fieldsets %}
            <div class="row">
              {% for field in fieldset %}
              <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group form-float">
                  {% comment %}
                    {% if field.errors %}
                      <p>{{ field.errors }}</p>
                    {% endif %}
                  {% endcomment %}

                  {% if field.field.widget.input_type == 'select' or field.field.widget.input_type == 'hidden' %}
                    {{field}}
                  {% elif field.field.widget.input_type == 'checkbox' %}
                    {{field}}
                    <label for="{{field.auto_id}}">{{field.label}}</label>
                  {% else %}
                    <div class="form-line">{{field}}
                      <label class="form-label">{{field.label}}</label>
                    </div>
                  {% endif %}

                  {% if field.help_text  %}
                    <p class="help-text" id="{{field.id_for_label}}">
                      {{field.help_text|safe}}
                    </p>
                  {% endif %}
                </div>
              </div>
              {% endfor %}
            </div>
          {% endfor %}
          <a href="{% url 'users:list' %}" class="btn btn-danger waves-effect">{% trans 'Cancel'%}</a>
          <button type="submit" class="btn btn-primary waves-effect">{% trans 'Send' %}</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'plugins/momentjs/moment.js' %}"></script>
<script src="{% static 'plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js' %}"></script>
<script>
  $(function () {
    $('#id_birth').bootstrapMaterialDatePicker({
        format: 'DD/MM/YYYY',
        clearButton: true,
        weekStart: 1,
        time: false
    });
  });
</script>

{% endblock %}

apps/users/templates/users/form_profile.html
{% extends "components/base.html" %}

{% load i18n %}

{% load static %}

{% block extra_css %}
  <link href="{% static 'plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css' %}" rel="stylesheet" />
{% endblock %}

{% block content %}
<div class="block-header">
</div>
<!-- Input -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        {% trans 'Form Perfil' as form_profile %}
        <h2>{{form_profile | upper}}</h2>
      </div>
      <div class="body">
        {% include "components/messages.html" with form=form %}
        <form id="form_email" class="" action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for fieldset in form.fieldsets %}
            <div class="row">
              {% for field in fieldset %}
              <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-group form-float">
                  {% comment %}
                    {% if field.errors %}
                      <p>{{ field.errors }}</p>
                    {% endif %}
                  {% endcomment %}

                  {% if field.field.widget.input_type == 'select' or field.field.widget.input_type == 'hidden' %}
                    {{field}}
                  {% elif field.field.widget.input_type == 'checkbox' %}
                    {{field}}
                    <label for="{{field.auto_id}}">{{field.label}}</label>
                  {% else %}
                    <div class="form-line">{{field}}
                      <label class="form-label">{{field.label}}</label>
                    </div>
                  {% endif %}

                  {% if field.help_text  %}
                    <p class="help-text" id="{{field.id_for_label}}">
                      {{field.help_text|safe}}
                    </p>
                  {% endif %}
                </div>
              </div>
              {% endfor %}
            </div>
          {% endfor %}
          <a href="{% url 'users:list' %}" class="btn btn-danger waves-effect">{% trans 'Cancel'%}</a>
          <button type="submit" class="btn btn-primary waves-effect">{% trans 'Send' %}</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'plugins/momentjs/moment.js' %}"></script>
<script src="{% static 'plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js' %}"></script>
<script>
  $(function () {
    $('#id_birth').bootstrapMaterialDatePicker({
        format: 'DD/MM/YYYY',
        clearButton: true,
        weekStart: 1,
        time: false
    });
  });
</script>

{% endblock %}

apps/users/templates/users/list.html
{% extends "components/base.html" %}

{% load i18n %}

{% load form_tags %}

{% block content %}

<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        {% trans "Search" as search %}
        <h2>{{search | upper }}</h2>
      </div>
      <div class="body">
        <form method="get" action="">
          <div class="row clearfix">
            {% for field in form_search %}
              <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                <div class="form-group form-float">
                {% if field.field.widget.input_type == 'select' %}
                  {{field}}
                {% elif field.field.widget.input_type == 'checkbox' %}
                  {{field}}
                  <label for="{{field.auto_id}}">{{field.label}}</label>
                  {% elif field.field.widget.input_type == 'text' %}
                  <div class="form-line">{{field}}
                    <label class="form-label">{{field.label}}</label>
                  </div>
                {% endif %}
                </div>
              </div>
            {% endfor %}

            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
              <button type="submit" class="btn btn-primary btn-lg m-l-15 waves-effect">{{search}}</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        {% trans "Users" as users_title %}
        <h2>{{users_title | upper}}</h2>
      </div>
      <div class="body table-responsive">
        {% include "components/messages.html" with form=None %}
        <table class="table">
          {% trans "First name" as first_name %}
          {% trans "Last name" as last_name %}
          {% trans "Email" as email %}
          {% trans "Actions" as actions %}
          <thead>
            <tr>
              <th>{{ first_name | upper }}</th>
              <th>{{ last_name | upper }}</th>
              <th>{{ email | upper }}</th>
              <th>{{ actions | upper }}</th>
            </tr>
          </thead>
          <tbody>
            {% for u in users %}
              <tr>
                <td>{{u.first_name}}</td>
                <td>{{u.last_name}}</td>
                <td>{{u.email}}</td>
                <td>
                  <div class="btn-group" role="group">
                    <a href="{% url 'users:detail' u.id %}" class="btn btn-default waves-effect btn-xs"><i class="material-icons">visibility</i></a>
                    {% if user.is_superuser %}
                      <a href="{% url 'users:change' u.id %}" class="btn btn-default waves-effect btn-xs"><i class="material-icons">lock</i></a>
                    {% endif %}
                    <a href="{% url 'users:edit' u.id %}" class="btn btn-info waves-effect btn-xs"><i class="material-icons">create</i></a>
                    <a href="{% url 'users:delete' u.id %}" class="btn btn-danger waves-effect btn-xs"><i class="material-icons">delete</i></a>
                  </div>
                </td>
              </tr>
            {% empty %}
            <tr>
              <td colspan="5">Sem usuários</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="footer">
      {% if is_paginated %}
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="waves-effect" ><a href="?{% url_replace page=page_obj.previous_page_number %}"><i class="material-icons">chevron_left</i></a></li>
          {% else %}
            <li class="disabled"><a href="#"><i class="material-icons">chevron_left</i></a></li>
          {% endif %}
            <li class="">
                <span>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
            </li>
          {% if page_obj.has_next %}
              <li class="waves-effect"><a href="?{% url_replace page=page_obj.next_page_number %}"><i class="material-icons">chevron_right</i></a></li>
          {% else %}
            <li class="waves-effect"><a href="#"><i class="material-icons">chevron_right</i></a></li>
          {% endif %}
        </ul>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}