apps/archives/urls.py
from django.urls import path
from apps.archives import views

app_name = 'archives'

urlpatterns = [
    path('', views.List.as_view(), name='list'),
    path('new', views.New.as_view(), name='new'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

apps/codes/urls.py
from django.urls import path
from apps.codes import views

app_name = 'codes'

urlpatterns = [
    path('', views.List.as_view(), name='list'),
    path('new', views.New.as_view(), name='new'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

apps/core/urls.py
from django.urls import path
from apps.core import views

app_name = 'core'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('mirror/generate/', views.MirrorFormView.as_view(), name='generate'),
]

apps/groups/urls.py
from django.urls import path
from apps.groups import views

app_name = 'groups'

urlpatterns = [
    path('', views.List.as_view(), name='list'),
    path('new/', views.New.as_view(), name='new'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    # path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

apps/users/urls.py
from django.urls import path
from apps.users import views

app_name = 'users'

urlpatterns = [
    path('', views.List.as_view(), name='list'),
    path('new/', views.New.as_view(), name='new'),
    path('profile/', views.EditProfile.as_view(), name='profile'),
    path('profile/password/', views.EditPass.as_view(), name='profile-pass'),
    path('edit/<int:pk>/', views.Edit.as_view(), name='edit'),
    path('detail/<int:pk>/', views.Detail.as_view(), name='detail'),
    path('change-pass/<int:pk>/', views.ChangePass.as_view(), name='change'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from apps.core import urls as core_urls
from apps.users import urls as users_urls
from apps.archives import urls as archives_urls
from apps.groups import urls as groups_urls
from apps.codes import urls as codes_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include(users_urls)),
    path(r'archives/', include(archives_urls)),
    path(r'groups/', include(groups_urls)),
    path(r'codes/', include(codes_urls)),
    path(r'', include(core_urls)),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models

# Create your models here.

apps/core/forms.py
"""forms core."""
from django import forms
from datetime import datetime
from apps.archives.models import Code
from django.utils.translation import ugettext_lazy as _


class FormCustomLogin(forms.Form):
    """form login."""

    username = forms.CharField(
        label=_('Username'), max_length=80, required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(
        label=_('Password'), max_length=80, required=True,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class FormMirror(forms.Form):
    """form mirror."""

    code1 = forms.ModelChoiceField(
        label=_('Code'),
        queryset=Code.objects.all(), required=True,
        widget=forms.Select(attrs={
            'class': 'form-control show-tick', 'required': True, }))
    box1 = forms.CharField(
        label=_('Box'), max_length=20, required=True,
        widget=forms.TextInput(attrs={
            'required': True, 'class': 'form-control'}))
    year1 = forms.CharField(
        label=_('Year'), required=True,
        initial=datetime.now().year, max_length=30,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'required': True, }))

    code2 = forms.ModelChoiceField(
        label=_('Code'),
        queryset=Code.objects.all(), required=True,
        widget=forms.Select(attrs={
            'class': 'form-control show-tick', 'required': True, }))
    box2 = forms.CharField(
        label=_('Box'), max_length=20, required=True,
        widget=forms.TextInput(attrs={
            'required': True, 'class': 'form-control'}))
    year2 = forms.CharField(
        label=_('Year'), required=True,
        initial=datetime.now().year, max_length=30,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'required': True, }))

    # code3 = forms.ModelChoiceField(
    #     label=_('Code'),
    #     queryset=Code.objects.all(), required=True,
    #     widget=forms.Select(attrs={
    #         'class': 'form-control show-tick', 'required': True, }))
    # box3 = forms.CharField(
    #     label=_('Box'), max_length=20, required=True,
    #     widget=forms.TextInput(attrs={
    #         'required': True, 'class': 'form-control'}))
    # year3 = forms.CharField(
    #     label=_('Year'), required=True,
    #     initial=datetime.now().year, max_length=30,
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control',
    #         'required': True, }))

    # code4 = forms.ModelChoiceField(
    #     label=_('Code'),
    #     queryset=Code.objects.all(), required=True,
    #     widget=forms.Select(attrs={
    #         'class': 'form-control show-tick', 'required': True, }))
    # box4 = forms.CharField(
    #     label=_('Box'), max_length=20, required=True,
    #     widget=forms.TextInput(attrs={
    #         'required': True, 'class': 'form-control'}))
    # year4 = forms.CharField(
    #     label=_('Year'), required=True,
    #     initial=datetime.now().year, max_length=30,
    #     widget=forms.TextInput(attrs={
    #         'class': 'form-control',
    #         'required': True, }))

    class Meta:
        fieldsets = (
          ('1', {
            'fields': ('code1', 'box1', 'year1')
          }),
          ('2', {
            'fields': ('code2', 'box2', 'year2')
          }),
          # ('3', {
          #   'fields': ('code3', 'box3', 'year3')
          # }),
          # ('4', {
          #   'fields': ('code4', 'box4', 'year4')
          # })
        )

apps/core/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth import authenticate, login, logout
from django.utils.decorators import method_decorator
from django.views.generic import FormView, RedirectView
from django.contrib.auth.decorators import login_required
from apps.core.forms import FormCustomLogin, FormMirror
from django.http import HttpResponseRedirect
from django.utils.translation import activate
from apps.archives.models import Code
from apps.archives.models import Archive
from django.contrib.auth.models import Group
from apps.users.models import User
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse_lazy
from urllib.parse import urlencode
import datetime


class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        activate('pt-br')
        return super(LoginRequiredMixin, self)\
            .dispatch(request, *args, **kwargs)


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "core/home.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['codes'] = Code.objects.all().count()
        context['users'] = User.objects.all().count()
        context['archives'] = Archive.objects.all().count()
        context['groups'] = Group.objects.all().count()
        return context


class LoginView(FormView):
    success_url = '/'
    # form_class = AuthenticationForm
    form_class = FormCustomLogin
    # redirect_field_name = REDIRECT_FIELD_NAME
    template_name = "core/login.html"

    def form_valid(self, form):
        data = form.cleaned_data

        user = authenticate(
            self.request,
            username=data['username'],
            password=data['password'])

        if user is not None:
            if user.is_active:
                login(self.request, user)
                return HttpResponseRedirect('/')
            else:
                msg = 'Conta inativa'
                messages.add_message(self.request, messages.WARNING, msg)
                return HttpResponseRedirect('/login/')
        else:
            msg = 'Senha incorreta'
            messages.add_message(self.request, messages.WARNING, msg)
            return HttpResponseRedirect('/login/')
        return super(LoginView, self).form_valid(form)


class LogoutView(LoginRequiredMixin, RedirectView):
    url = '/login/'
    permanent = True

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class MirrorFormView(LoginRequiredMixin, FormView):
    template_name = "core/form_mirror.html"
    form_class = FormMirror

    def form_valid(self, form):
        data = form.cleaned_data

        # url = "http://stackoverflow.com/search?q=question"
        # params = {'lang':'en','tag':'python'}
        #
        # url_parts = list(urlparse.urlparse(url))
        query = urlencode(data, doseq=True)
        print(query)
        # query.update(params)
        #
        # url_parts[4] = urlencode(query)
        # reverse_lazy('codes:list')

        return render(
            self.request, 'core/mirror3.html', data,
            content_type="text/html")

apps/core/templates/components/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <title>CRM</title>
  <!-- Favicon-->
  <link rel="icon" href="../../favicon.ico" type="image/x-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">

  <!-- Bootstrap Core Css -->
  <link href="{% static 'plugins/bootstrap/css/bootstrap.css' %}" rel="stylesheet">

  <!-- Waves Effect Css -->
  <link href="{% static 'plugins/node-waves/waves.css' %}" rel="stylesheet" />

  <!-- Animation Css -->
  <link href="{% static 'plugins/animate-css/animate.css' %}" rel="stylesheet" />

  <!-- Custom Css -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <link href="{% static 'plugins/bootstrap-select/css/bootstrap-select.css' %}" rel="stylesheet" />

  <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
  <link href="{% static 'css/themes/all-themes.css' %}" rel="stylesheet" />

  {% block extra_css %}

  {% endblock %}
</head>

<body class="theme-red">
  <!-- Page Loader -->
  <div class="page-loader-wrapper">
    <div class="loader">
      <div class="preloader">
        <div class="spinner-layer pl-red">
          <div class="circle-clipper left">
            <div class="circle"></div>
          </div>
          <div class="circle-clipper right">
            <div class="circle"></div>
          </div>
        </div>
      </div>
      <p>Please wait...</p>
    </div>
  </div>
  <!-- #END# Page Loader -->
  <!-- Overlay For Sidebars -->
  <div class="overlay"></div>
  <!-- #END# Overlay For Sidebars -->
  <!-- Search Bar -->
  <div class="search-bar">
    <div class="search-icon">
      <i class="material-icons">search</i>
    </div>
    <input type="text" placeholder="START TYPING...">
    <div class="close-search">
      <i class="material-icons">close</i>
    </div>
  </div>
  <!-- #END# Search Bar -->
  <!-- Top Bar -->
  {% include 'components/topbar.html' %}
  <!-- #Top Bar -->
  <section>
    <!-- Left Sidebar -->
    {% include 'components/sidebar-left.html' %}
    <!-- #END# Left Sidebar -->
    <!-- Right Sidebar -->
    {% include 'components/sidebar-rigth.html' %}
    <!-- #END# Right Sidebar -->
  </section>

  <section class="content">
    <div class="container-fluid">
      {% block content %}

      {% endblock %}
    </div>
  </section>

  <!-- Jquery Core Js -->
  <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

  <!-- Bootstrap Core Js -->
  <script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>

  <!-- Select Plugin Js -->
  <script src="{% static 'plugins/bootstrap-select/js/bootstrap-select.js' %}"></script>

  <!-- Slimscroll Plugin Js -->
  <script src="{% static 'plugins/jquery-slimscroll/jquery.slimscroll.js' %}"></script>

  <!-- Waves Effect Plugin Js -->
  <script src="{% static 'plugins/node-waves/waves.js' %}"></script>

  <!-- Custom Js -->
  <script src="{% static 'js/admin.js' %}"></script>

  <!-- Demo Js -->
  <script src="{% static 'js/demo.js' %}"></script>

  {% block extra_js %}

  {% endblock %}
</body>

</html>

apps/core/templates/components/messages.html
{% load form_tags %}

<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-warning alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h5>Mensagem</h5>
          {{ message }}
        </div>
      {% endfor %}
      {# <script>setTimeout(function(){$(".callout").remove();}, 5000);</script> #}
    {% endif %}

    {% if form and form.errors %}
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5>Alerta</h5>
        <ul>
          {% for key, value in form.errors.items %}
          <li>{% get_label key form %} : {{ value|escape }}</li>
          {% endfor %}
        </ul>
        {# <li>{{ key|escape }} {% get_label key form %} : {{ value|escape }}</li> #}
      </div>
    {% endif %}

    {% comment %}
    {% for error in form.non_field_errors %}
        <li>{{ key|escape }} : {{ value|escape }}</li>
    {% endfor %}
    {% endcomment %}
  </div>
</div>

apps/core/templates/components/sidebar-left.html
{% load i18n %}
<aside id="leftsidebar" class="sidebar">
  <!-- User Info -->
  <div class="user-info">
    <div class="image">
        {# <img src="../../images/user.png" width="48" height="48" alt="User" /> #}
    </div>
    <div class="info-container">
      <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{user.full_name}}</div>
      <div class="email">{{user.email}}</div>
      <div class="btn-group user-helper-dropdown">
        <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
        <ul class="dropdown-menu pull-right">
          <li><a href="{% url 'users:profile' %}"><i class="material-icons">person</i>{% trans "Profile" %}</a></li>
          <li role="seperator" class="divider"></li>
          <li><a href="{% url 'users:profile-pass' %}"><i class="material-icons">lock</i>{% trans "Change Password" %}</a></li>
          <li role="seperator" class="divider"></li>
          <li><a href="{% url 'core:logout' %}"><i class="material-icons">input</i>{% trans "Sign Out" %}</a></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- #User Info -->
  <!-- Menu -->
  <div class="menu">
    <ul class="list">
      <li class="header">{% trans "NAVIGATION" %}</li>
      <li class="active">
        <a href="{% url 'core:home' %}">
          <i class="material-icons">home</i>
          <span>{% trans "Home" %}</span>
        </a>
      </li>
      {% if user.is_superuser %}
      <li>
        <a href="javascript:void(0);" class="menu-toggle">
          <i class="material-icons">people</i>
          <span>{% trans "Users" %}</span>
        </a>
        <ul class="ml-menu">
          <li>
            <a href="{% url 'users:list' %}">{% trans "List users" %}</a>
          </li>
          <li>
            <a href="{% url 'users:new' %}">{% trans "New user" %}</a>
          </li>
        </ul>
      </li>
      {% endif %}
      <li>
        <a href="javascript:void(0);" class="menu-toggle">
          <i class="material-icons">folder</i>
          <span>{% trans "Archives" %}</span>
        </a>
        <ul class="ml-menu">
          <li>
            <a href="{% url 'archives:list' %}">{% trans "List archives" %}</a>
          </li>
          <li>
            <a href="{% url 'archives:new' %}">{% trans "New archive" %}</a>
          </li>
        </ul>
      </li>
      {% if user.is_superuser %}
      <li>
        <a href="javascript:void(0);" class="menu-toggle">
          <i class="material-icons">group_work</i>
          <span>{% trans "Groups" %}</span>
        </a>
        <ul class="ml-menu">
          <li>
            <a href="{% url 'groups:list' %}">{% trans "List groups" %}</a>
          </li>
          <li>
            <a href="{% url 'groups:new' %}">{% trans "New group" %}</a>
          </li>
        </ul>
      </li>
      {% endif %}
      <li>
        <a href="{% url 'core:generate' %}">
          <i class="material-icons">class</i>
          <span>{% trans "Mirror" %}</span>
        </a>
      </li>
      {% if user.is_superuser %}
      <li>
        <a href="javascript:void(0);" class="menu-toggle">
          <i class="material-icons">receipt</i>
          <span>{% trans "Codes" %}</span>
        </a>
        <ul class="ml-menu">
          <li>
            <a href="{% url 'codes:list' %}">{% trans "List codes" %}</a>
          </li>
          <li>
            <a href="{% url 'codes:new' %}">{% trans "New code" %}</a>
          </li>
        </ul>
      </li>
      {% endif %}
    </ul>
  </div>
  <!-- #Menu -->
  <!-- Footer -->
  <div class="legal">
    <div class="copyright">
      <img src="/static/img/logo.png" style="height: 50px;" />
      <br>
      (86) 9 8806-3493 - Lindemberg Gomes
      <br>
      (86) 9 8127-7728 - Madson Henrique
      <br>
      email: arquivcerto@outlook.com.
      <br>
      &copy; 2018 <a href="#">Arquiv Certo</a>.
    </div>
    <div class="version">
      <b>Version: </b> 1.2.1
    </div>
  </div>
  <!-- #Footer -->
</aside>

apps/core/templates/components/sidebar-rigth.html
<aside id="rightsidebar" class="right-sidebar">
    <ul class="nav nav-tabs tab-nav-right" role="tablist">
        <li role="presentation" class="active"><a href="#skins" data-toggle="tab">SKINS</a></li>
        <li role="presentation"><a href="#settings" data-toggle="tab">SETTINGS</a></li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active in active" id="skins">
            <ul class="demo-choose-skin">
                <li data-theme="red" class="active">
                    <div class="red"></div>
                    <span>Red</span>
                </li>
                <li data-theme="pink">
                    <div class="pink"></div>
                    <span>Pink</span>
                </li>
                <li data-theme="purple">
                    <div class="purple"></div>
                    <span>Purple</span>
                </li>
                <li data-theme="deep-purple">
                    <div class="deep-purple"></div>
                    <span>Deep Purple</span>
                </li>
                <li data-theme="indigo">
                    <div class="indigo"></div>
                    <span>Indigo</span>
                </li>
                <li data-theme="blue">
                    <div class="blue"></div>
                    <span>Blue</span>
                </li>
                <li data-theme="light-blue">
                    <div class="light-blue"></div>
                    <span>Light Blue</span>
                </li>
                <li data-theme="cyan">
                    <div class="cyan"></div>
                    <span>Cyan</span>
                </li>
                <li data-theme="teal">
                    <div class="teal"></div>
                    <span>Teal</span>
                </li>
                <li data-theme="green">
                    <div class="green"></div>
                    <span>Green</span>
                </li>
                <li data-theme="light-green">
                    <div class="light-green"></div>
                    <span>Light Green</span>
                </li>
                <li data-theme="lime">
                    <div class="lime"></div>
                    <span>Lime</span>
                </li>
                <li data-theme="yellow">
                    <div class="yellow"></div>
                    <span>Yellow</span>
                </li>
                <li data-theme="amber">
                    <div class="amber"></div>
                    <span>Amber</span>
                </li>
                <li data-theme="orange">
                    <div class="orange"></div>
                    <span>Orange</span>
                </li>
                <li data-theme="deep-orange">
                    <div class="deep-orange"></div>
                    <span>Deep Orange</span>
                </li>
                <li data-theme="brown">
                    <div class="brown"></div>
                    <span>Brown</span>
                </li>
                <li data-theme="grey">
                    <div class="grey"></div>
                    <span>Grey</span>
                </li>
                <li data-theme="blue-grey">
                    <div class="blue-grey"></div>
                    <span>Blue Grey</span>
                </li>
                <li data-theme="black">
                    <div class="black"></div>
                    <span>Black</span>
                </li>
            </ul>
        </div>
        <div role="tabpanel" class="tab-pane fade" id="settings">
            <div class="demo-settings">
                <p>GENERAL SETTINGS</p>
                <ul class="setting-list">
                    <li>
                        <span>Report Panel Usage</span>
                        <div class="switch">
                            <label><input type="checkbox" checked><span class="lever"></span></label>
                        </div>
                    </li>
                    <li>
                        <span>Email Redirect</span>
                        <div class="switch">
                            <label><input type="checkbox"><span class="lever"></span></label>
                        </div>
                    </li>
                </ul>
                <p>SYSTEM SETTINGS</p>
                <ul class="setting-list">
                    <li>
                        <span>Notifications</span>
                        <div class="switch">
                            <label><input type="checkbox" checked><span class="lever"></span></label>
                        </div>
                    </li>
                    <li>
                        <span>Auto Updates</span>
                        <div class="switch">
                            <label><input type="checkbox" checked><span class="lever"></span></label>
                        </div>
                    </li>
                </ul>
                <p>ACCOUNT SETTINGS</p>
                <ul class="setting-list">
                    <li>
                        <span>Offline</span>
                        <div class="switch">
                            <label><input type="checkbox"><span class="lever"></span></label>
                        </div>
                    </li>
                    <li>
                        <span>Location Permission</span>
                        <div class="switch">
                            <label><input type="checkbox" checked><span class="lever"></span></label>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</aside>

apps/core/templates/components/topbar.html
{% load i18n %}
<nav class="navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
      <a href="javascript:void(0);" class="bars"></a>
      <a class="navbar-brand" href="{% url 'core:home'%}">CRM</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <!-- Call Search -->
        {# <li><a href="javascript:void(0);" class="js-search" data-close="true"><i class="material-icons">search</i></a></li>#}
        <!-- #END# Call Search -->
        <!-- Notifications -->
        {% comment %}
        <li class="dropdown">
          <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
            <i class="material-icons">notifications</i>
            <span class="label-count">7</span>
          </a>
          <ul class="dropdown-menu">
              <li class="header">NOTIFICATIONS</li>
              <li class="body">
                  <ul class="menu">
                      <li>
                          <a href="javascript:void(0);">
                              <div class="icon-circle bg-light-green">
                                  <i class="material-icons">person_add</i>
                              </div>
                              <div class="menu-info">
                                  <h4>12 new members joined</h4>
                                  <p>
                                      <i class="material-icons">access_time</i> 14 mins ago
                                  </p>
                              </div>
                          </a>
                      </li>
                      <li>
                          <a href="javascript:void(0);">
                              <div class="icon-circle bg-cyan">
                                  <i class="material-icons">add_shopping_cart</i>
                              </div>
                              <div class="menu-info">
                                  <h4>4 sales made</h4>
                                  <p>
                                      <i class="material-icons">access_time</i> 22 mins ago
                                  </p>
                              </div>
                          </a>
                      </li>
                      <li>
                          <a href="javascript:void(0);">
                              <div class="icon-circle bg-red">
                                  <i class="material-icons">delete_forever</i>
                              </div>
                              <div class="menu-info">
                                  <h4><b>Nancy Doe</b> deleted account</h4>
                                  <p>
                                      <i class="material-icons">access_time</i> 3 hours ago
                                  </p>
                              </div>
                          </a>
                      </li>
                      <li>
                          <a href="javascript:void(0);">
                              <div class="icon-circle bg-orange">
                                  <i class="material-icons">mode_edit</i>
                              </div>
                              <div class="menu-info">
                                  <h4><b>Nancy</b> changed name</h4>
                                  <p>
                                      <i class="material-icons">access_time</i> 2 hours ago
                                  </p>
                              </div>
                          </a>
                      </li>
                      <li>
                          <a href="javascript:void(0);">
                              <div class="icon-circle bg-blue-grey">
                                  <i class="material-icons">comment</i>
                              </div>
                              <div class="menu-info">
                                  <h4><b>John</b> commented your post</h4>
                                  <p>
                                      <i class="material-icons">access_time</i> 4 hours ago
                                  </p>
                              </div>
                          </a>
                      </li>
                      <li>
                          <a href="javascript:void(0);">
                              <div class="icon-circle bg-light-green">
                                  <i class="material-icons">cached</i>
                              </div>
                              <div class="menu-info">
                                  <h4><b>John</b> updated status</h4>
                                  <p>
                                      <i class="material-icons">access_time</i> 3 hours ago
                                  </p>
                              </div>
                          </a>
                      </li>
                      <li>
                          <a href="javascript:void(0);">
                              <div class="icon-circle bg-purple">
                                  <i class="material-icons">settings</i>
                              </div>
                              <div class="menu-info">
                                  <h4>Settings updated</h4>
                                  <p>
                                      <i class="material-icons">access_time</i> Yesterday
                                  </p>
                              </div>
                          </a>
                      </li>
                  </ul>
              </li>
              <li class="footer">
                  <a href="javascript:void(0);">View All Notifications</a>
              </li>
          </ul>
        </li>
        {% endcomment %}
        <!-- #END# Notifications -->
      </ul>
    </div>
  </div>
</nav>